version: '3.8'
services:

  db:
    container_name: db
    image: pgvector/pgvector:pg17
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: kayros
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: kayros #optional (specify default database instead of $POSTGRES_DB)
    volumes:
      - pgdata:/var/lib/postgresql/data # Configure a named volume called "db-data"
    networks:
      - backend-network

  rabbitmq:
    image: rabbitmq:4.0.9-management # Utiliza la imagen con la interfaz de gesti칩n
    container_name: rabbitmq
    ports:
      - "5672:5672"   # Puerto para la comunicaci칩n con las aplicaciones (AMQP)
      - "15672:15672" # Puerto para la interfaz de gesti칩n web
    environment:
      - RABBITMQ_DEFAULT_USER=guest # Usuario por defecto
      - RABBITMQ_DEFAULT_PASS=guest # Contrase침a por defecto
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
    networks:
      - backend-network

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@kayros.com
      PGADMIN_DEFAULT_PASSWORD: 12345
    ports:
      - '8080:80'
    user: root
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - backend-network
    depends_on:
      - db

  eureka-one:
    container_name: eureka-one
    image: eureka:1.3.0
    restart: unless-stopped
    ports:
      - 4001:4001
    environment:
        - SPRING_PROFILES_ACTIVE=eureka-one
    networks:
      - backend-network

  eureka-two:
    container_name: eureka-two
    image: eureka:1.3.0
    restart: unless-stopped
    ports:
      - 4002:4002
    environment:
      - SPRING_PROFILES_ACTIVE=eureka-two
    networks:
      - backend-network

  eureka-three:
    container_name: eureka-three
    image: eureka:1.3.0
    restart: unless-stopped
    ports:
      - 4003:4003
    environment:
      - SPRING_PROFILES_ACTIVE=eureka-three
    networks:
      - backend-network

  authorization-server:
    container_name: authorization-server
    image: authorization-server:1.3.0
    restart: unless-stopped
    ports:
      - 9100:9100
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - backend-network

  kairos-calendar:
    container_name: kairos-calendar
    image: kairos-calendar:1.3.0
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - db
      - rabbitmq
      - eureka-one
    networks:
      - backend-network

  kairos-employee:
    container_name: kairos-employee
    image: kairos-employee:1.3.0
    restart: unless-stopped
    ports:
      - 8083:8083
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - db
      - rabbitmq
      - eureka-one
    networks:
      - backend-network

  kairos-clock:
    container_name: kairos-clock
    image: kairos-clock:1.3.0
    restart: unless-stopped
    ports:
      - 8082:8082
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - db
      - rabbitmq
      - eureka-one
    networks:
      - backend-network

networks:
  backend-network:
    ipam:
      config:
        - subnet: 192.168.20.0/24
volumes:
  rabbitmq_data:
  pgdata:
  pgadmin:
