spring:
  application:
     name: resource-server

zuul:
  prefix: /gw
  ignored-services: /**
  routes:
    clanedar:
      service-id: kairos-calendar-service
      path: /cal/**
    clock:
      service-id: kairos-clock-service
      path: /clo/**
    employee:
      service-id: kairos-calendar-service
      path: /emp/**
    oauth2:
      service-id: authorization-server
      path: /sec/**
      sensitive-headers: Cookie,Set-Cookie            
      
config:
  security:
    oauth:
      jwt:
        key: clave_firma_jwt        
        
server:
  port: 1234  
  error:
    whitelabel:
      enabled: false
      
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}    
  client:   
    serviceUrl:
      defaultZone: http://eureka-primary:4002/eureka

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([trace=%X{X-Trace-Id:-},span=%X{X-Span-Id:-}]){yellow} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%replace(%xException){'\n','\u2028'}%nopex%n"
  
     