logging:
  level:
    es:
      ozona: debug
    root: warn
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([trace=%X{X-Trace-Id:-},span=%X{X-Span-Id:-}]){yellow} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%replace(%xException){'\n','\u2028'}%nopex%n"    

server:
  port: 8083

feign:
  hystrix:
    enabled: true
  
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
        
kairos-calendar-service:
  ribbon:
    ReadTimeout: 1000
    ConnectTimeout: 1000   
    MaxAutoRetriesNextServer: 4
    MaxAutoRetries: 2

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    service-url:
      defaultZone: http://eureka-primary:4002/eureka
  
spring:
  application:
    name: kairos-employee-service
  cloud:
    stream:
      bindings:
        employeeManagementOutChannel:
          destination: employeeManagement    
          binder: rabbit
        timesheetManagementInputChannel:
          destination: timesheetManagement
          binder: rabbit
          group: employeeService
      binders:
        rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
  datasource:
    url: jdbc:h2:file:C:/proyectos/employeedb;DB_CLOSE_DELAY=2;AUTO_SERVER=TRUE #DB_CLOSE_ON_EXIT=false
    username: sa
    password:
    driverClassName: org.h2.Driver     
  jpa:
    generate-ddl: true
    show-sql: true
    open-in-view: true          
    database-platform: es.ozona.kairos.employee.MyH2Dialect
    hibernate:      
      ddl-auto: create-drop
#    properties:
#      hibernate:
#        hbm2ddl:
#          auto: update   
#      javax:
#        persistence:      
#          schema-generation:
#            database:
#              action: drop-and-create                
#            drop-source: metadata
#            create-source: metadata
#            scripts:
#              action: drop-and-create
#              create-target: ./src/test/resources/dll/create.sql
#              drop-target: ./src/test/resources/dll/drop.sql
  h2:
    console:
      enabled: true
      path: /h2-console

