create sequence hibernate_sequence start with 1 increment by 1
create table calendar (id bigint not null, calendar_id varchar(500), year integer, primary key (id))
create table holiday (id bigint not null, holiday timestamp, calendar_id bigint, primary key (id))
create table shiftplan (id bigint not null, calendar_id varchar(500), end_date timestamp, shiftplan_id varchar(500), start_date timestamp, primary key (id))
create table shiftplan_workday (id bigint not null, end timestamp, start timestamp, day_of_week integer, rest_time time, entry timestamp, exit timestamp, shiftplan_id bigint, primary key (id))
alter table holiday add constraint FKt1fbx4nnokx3whwybsdw3vexg foreign key (calendar_id) references calendar
alter table shiftplan_workday add constraint FK4r8yhv2k098vwliquhlunp1bn foreign key (shiftplan_id) references shiftplan
create sequence calendar_id_seq start with 1 increment by 50
create sequence holiday_id_seq start with 1 increment by 50
create sequence shiftplan_id_seq start with 1 increment by 50
create sequence workday_id_seq start with 1 increment by 50
create table calendar (id bigint not null, calendar_id varchar(500), year integer, primary key (id))
create table holiday (id bigint not null, holiday timestamp, calendar_id bigint, primary key (id))
create table shiftplan (id bigint not null, calendar_id varchar(500), end_date timestamp, shiftplan_id varchar(500), start_date timestamp, primary key (id))
create table shiftplan_workday (id bigint not null, end timestamp, start timestamp, day_of_week integer, rest_time time, entry timestamp, exit timestamp, shiftplan_id bigint, primary key (id))
alter table holiday add constraint FKt1fbx4nnokx3whwybsdw3vexg foreign key (calendar_id) references calendar
alter table shiftplan_workday add constraint FK4r8yhv2k098vwliquhlunp1bn foreign key (shiftplan_id) references shiftplan
create table calendar (id bigint generated by default as identity, calendar_id varchar(500), year integer, primary key (id))
create table holiday (id bigint generated by default as identity, holiday timestamp, calendar_id bigint, primary key (id))
create table shiftplan (id bigint generated by default as identity, calendar_id varchar(500), end_date timestamp, shiftplan_id varchar(500), start_date timestamp, primary key (id))
create table shiftplan_workday (id bigint generated by default as identity, end timestamp, start timestamp, day_of_week integer, rest_time time, entry timestamp, exit timestamp, shiftplan_id bigint, primary key (id))
alter table holiday add constraint FKt1fbx4nnokx3whwybsdw3vexg foreign key (calendar_id) references calendar
alter table shiftplan_workday add constraint FK4r8yhv2k098vwliquhlunp1bn foreign key (shiftplan_id) references shiftplan
create table calendar (id bigint generated by default as identity, calendar_id varchar(500), year integer, primary key (id))
create table holiday (id bigint generated by default as identity, holiday timestamp, calendar_id bigint, primary key (id))
create table shiftplan (id bigint generated by default as identity, calendar_id varchar(500), end_date timestamp, shiftplan_id varchar(500), start_date timestamp, primary key (id))
create table shiftplan_workday (id bigint generated by default as identity, end timestamp, start timestamp, day_of_week integer, rest_time time, entry timestamp, exit timestamp, shiftplan_id bigint, primary key (id))
alter table holiday add constraint FKt1fbx4nnokx3whwybsdw3vexg foreign key (calendar_id) references calendar
alter table shiftplan_workday add constraint FK4r8yhv2k098vwliquhlunp1bn foreign key (shiftplan_id) references shiftplan
create table calendar (id bigint generated by default as identity, calendar_id varchar(500), year integer, primary key (id))
create table holiday (id bigint generated by default as identity, holiday timestamp, calendar_id bigint, primary key (id))
create table shiftplan (id bigint generated by default as identity, calendar_id varchar(500), end_date timestamp, shiftplan_id varchar(500), start_date timestamp, primary key (id))
create table shiftplan_workday (id bigint generated by default as identity, end timestamp, start timestamp, day_of_week integer, rest_time time, entry timestamp, exit timestamp, shiftplan_id bigint, primary key (id))
alter table holiday add constraint FKt1fbx4nnokx3whwybsdw3vexg foreign key (calendar_id) references calendar
alter table shiftplan_workday add constraint FK4r8yhv2k098vwliquhlunp1bn foreign key (shiftplan_id) references shiftplan
create table calendar (id bigint generated by default as identity, calendar_id varchar(500), year integer, primary key (id))
create table holiday (id bigint generated by default as identity, holiday timestamp, calendar_id bigint, primary key (id))
create table shiftplan (id bigint generated by default as identity, calendar_id varchar(500), end_date timestamp, shiftplan_id varchar(500), start_date timestamp, primary key (id))
create table shiftplan_workday (id bigint generated by default as identity, end timestamp, start timestamp, day_of_week integer, rest_time time, entry timestamp, exit timestamp, shiftplan_id bigint, primary key (id))
alter table holiday add constraint FKt1fbx4nnokx3whwybsdw3vexg foreign key (calendar_id) references calendar
alter table shiftplan_workday add constraint FK4r8yhv2k098vwliquhlunp1bn foreign key (shiftplan_id) references shiftplan
create table calendar (id bigint generated by default as identity, calendar_id varchar(500), year integer, primary key (id))
create table holiday (id bigint generated by default as identity, holiday timestamp, calendar_id bigint, primary key (id))
create table shiftplan (id bigint generated by default as identity, calendar_id varchar(500), end_date timestamp, shiftplan_id varchar(500), start_date timestamp, primary key (id))
create table shiftplan_workday (id bigint generated by default as identity, end timestamp, start timestamp, day_of_week integer, rest_time time, entry timestamp, exit timestamp, shiftplan_id bigint, primary key (id))
alter table holiday add constraint FKt1fbx4nnokx3whwybsdw3vexg foreign key (calendar_id) references calendar
alter table shiftplan_workday add constraint FK4r8yhv2k098vwliquhlunp1bn foreign key (shiftplan_id) references shiftplan
create table calendar (id bigint generated by default as identity, calendar_id varchar(500), year integer, primary key (id))
create table holiday (id bigint generated by default as identity, holiday timestamp, calendar_id bigint, primary key (id))
create table shiftplan (id bigint generated by default as identity, calendar_id varchar(500), end_date timestamp, shiftplan_id varchar(500), start_date timestamp, primary key (id))
create table shiftplan_workday (id bigint generated by default as identity, end timestamp, start timestamp, day_of_week integer, rest_time time, entry timestamp, exit timestamp, shiftplan_id bigint, primary key (id))
alter table holiday add constraint FKt1fbx4nnokx3whwybsdw3vexg foreign key (calendar_id) references calendar
alter table shiftplan_workday add constraint FK4r8yhv2k098vwliquhlunp1bn foreign key (shiftplan_id) references shiftplan
