spring:
  profiles: 
    active: @spring.profiles.active@

--- # profile dev

spring:
  profiles: dev
server:
  
  port: 4001
eureka:
  instance:
    hostname: eureka-one
  client:    
    fetch-registry: true
    register-with-eureka: false

--- # profile eurekaone

spring:
  profiles: eureka-one
server:
  
  port: 4001
eureka:
  instance:
    hostname: eureka-one
  client:    
    fetch-registry: true
    register-with-eureka: false    
    serviceUrl:
      defaultZone: http://eureka-two:4002/eureka,http://eureka-three:4003/eureka
 
--- # profile eurekatwo

spring:
  profiles: eureka-two
server:
  port: 4002
eureka:  
  instance:    
    hostname: eureka-two
  client:
    fetch-registry: true
    register-with-eureka: false    
    serviceUrl:
      defaultZone: http://eureka-one:4001/eureka,http://eureka-three:4003/eureka
    
--- # profile eurekathree

spring:
  profiles: eureka-three
server:
  port: 4003
eureka:
  instance:   
    hostname: eureka-three
  client:
    fetch-registry: true
    register-with-eureka: false    
    serviceUrl:
      defaultZone: http://eureka-one:4001/eureka,http://eureka-two:4002/eureka
    