spring:
  profiles: 
    active: eureka-one

--- # profile eurekaone

spring:
  profiles: eureka-one
server:
  port: 4001
eureka:
  instance:
    hostname: eureka-one
  client:    
    fetch-registry: true
    register-with-eureka: false    
#    serviceUrl:
#      defaultZone: http://eureka-secondary:4003/eureka,http://eureka-tertiary:4004/eureka
 
--- # profile eurekatwo

spring:
  profiles: eureka-two
server:
  port: 4002
eureka:  
  instance:    
    hostname: eureka-two
  client:
    fetch-registry: true
    register-with-eureka: false    
    serviceUrl:
      defaultZone: http://eureka-primary:4002/eureka,http://eureka-tertiary:4004/eureka
    
--- # profile eurekathree

spring:
  profiles: eureka-three
server:
  port: 4003
eureka:
  instance:   
    hostname: eureka-three
  client:
    fetch-registry: true
    register-with-eureka: false    
    serviceUrl:
      defaultZone: http://eureka-primary:4002/eureka,http://eureka-secondary:4003/eureka
    