drop table calendar if exists
drop table holiday if exists
drop table shiftplan if exists
drop table shiftplan_workday if exists
drop table calendar if exists
drop table holiday if exists
drop table shiftplan if exists
drop table shiftplan_workday if exists
drop table calendar if exists
drop table holiday if exists
drop table shiftplan if exists
drop table shiftplan_workday if exists
