spring:
  profiles:
    active: @spring.profiles.active@

server:
  servlet:
    context-path: /auth
    session:
      cookie:
        path: /auth

--- # insecure

server:
  port: 9100

spring:
  application:
    name: authorization-server
  profiles: insecure

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:4001/eureka
      
security:
  oauth2:
    client:
      client-id: kayrosclientid
      client-secret: secret
      registered-redirect-uri: http://192.168.0.22:8080/kayros/login/oauth2/code/kayrosclient

--- # dev

server:
  port: 9443
  ssl:
    # key store
    key-store: classpath:keystore.p12
    key-store-password: secret
    key-store-type: PKCS12
    key-alias: authorization-server
    # trust store
    trust-store: classpath:truststore.p12
    trust-store-password: secret
    trust-store-type: PKCS12
    client-auth: want

spring:
  application:
    name: authorization-server
  profiles: dev

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:4001/eureka
      
security:
  oauth2:
    client:
      client-id: kayrosclientid
      client-secret: secret
      registered-redirect-uri: https://localhost:8443/kayros/login/oauth2/code/kayrosclient

--- # test
server:
  port: 9443
  ssl:
    # key store
    key-store: classpath:keystore.p12
    key-store-password: secret
    key-store-type: PKCS12
    key-alias: authorization-server
    # trust store
    trust-store: classpath:truststore.p12
    trust-store-password: secret
    trust-store-type: PKCS12
    client-auth: want

spring:
  application:
    name: authorization-server
  profiles: test

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-one:4001/eureka
      
security:
  oauth2:
    client:
      client-id: kayrosclientid
      client-secret: secret
      registered-redirect-uri: https://192.168.0.22:8443/kayros/login/oauth2/code/kayrosclient
          
--- # prod
server:
  port: 9443
  ssl:
    # key store
    key-store: classpath:keystore.p12
    key-store-password: secret
    key-store-type: PKCS12
    key-alias: authorization-server
    # trust store
    trust-store: classpath:truststore.p12
    trust-store-password: secret
    trust-store-type: PKCS12
    client-auth: want

spring:
  application:
    name: authorization-server
  profiles: prod

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-one:4001/eureka
      
security:
  oauth2:
    client:
      client-id: kayrosclientid
      client-secret: secret
      registered-redirect-uri: https://dockernode2.flowteam.ozona.es/kayros/login/oauth2/code/kayrosclient
   

# $> keytool -genkey -alias oauth2server -storetype PKCS12 -keyalg RSA -keysize 2048 -keystore oauth2keystore.p12
#    keytool -genkey -keyalg RSA -storetype PKCS12 -alias authorization-server -keystore keystore.p12 -storepass secret -validity 360
#    keytool -genkey -keyalg RSA -storetype PKCS12 -alias kayros-webapp -keystore keystore.p12 -storepass secret -validity 360
#    keytool -export -alias kayros-webapp -file kayros-webapp.crt -keystore keystore.p12 -storepass secret
#    keytool -import -storetype PKCS12  -alias kayros-webapp -file kayros-webapp.crt -keystore truststore.p12 -storepass secret