spring:
  profiles:
    active: @spring.profiles.active@

--- # dev

server:
  port: 9100
  servlet:
    context-path: /auth
    session:
      cookie:
        path: /auth

spring:
  application:
    name: authorization-server
  profiles: dev

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:4001/eureka
      
security:
  oauth2:
    client:
      client-id: kayrosclientid
      client-secret: secret
      registered-redirect-uri: https://localhost:8443/kayros/login/oauth2/code/kayrosclient

--- # test

server:
  port: 9100
  servlet:
    context-path: /auth
    session:
      cookie:
        path: /auth

spring:
  application:
    name: authorization-server
  profiles: test

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-one:4001/eureka
      
security:
  oauth2:
    client:
      client-id: kayrosclientid
      client-secret: secret
      registered-redirect-uri: https://192.168.0.22:8443/kayros/login/oauth2/code/kayrosclient
          
--- # prod

server:
  port: 9100
  servlet:
    context-path: /auth
    session:
      cookie:
        path: /auth

spring:
  application:
    name: authorization-server
  profiles: prod

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-one:4001/eureka
      
security:
  oauth2:
    client:
      client-id: kayrosclientid
      client-secret: secret
      registered-redirect-uri: https://dockernode2.flowteam.ozona.es:8443/kayros/login/oauth2/code/kayrosclient
   

# $> keytool -genkey -alias oauth2server -storetype PKCS12 -keyalg RSA -keysize 2048 -keystore oauth2keystore.p12