#see: https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-primary:4002/eureka

zk:
  homepage: login
  zul-view-resolver-prefix: /zul

server:
  servlet:
    context-path: /kayros
    session:
      cookie:
        path: /kayros
  port: 8443
  ssl:
    key-store-password: zWx6bv-YTePQ%1qtGtnI
    key-store: classpath:kayrosWebappKeyStore.p12
    key-store-type: PKCS12
    key-alias: kayros-webapp

feign:
  hystrix:
    enabled: true
    
kairos-clock-service:
  ribbon:
    ReadTimeout: 1000
    ConnectTimeout: 1000   
    MaxAutoRetriesNextServer: 4
    MaxAutoRetries: 2
    
kairos-employee-service:
  ribbon:
    ReadTimeout: 1000
    ConnectTimeout: 1000   
    MaxAutoRetriesNextServer: 4
    MaxAutoRetries: 2
    
spring:
  application:
    name: kairos-webapp
  security: 
    oauth2:
      client:
        registration:
          kayrosclient:
            client-id: kayrosclientid
            client-secret: secret
            client-name: kayros
            scope: user_info,read,write
            redirect-uri: https://localhost:8443/kayros/login/oauth2/code/kayrosclient
            client-authentication-method: basic
            authorization-grant-type: authorization_code
            provider: kayros-authserver-provider
        provider:
            kayros-authserver-provider:
              token-uri: http://localhost:9100/auth/oauth/token
              authorization-uri: http://localhost:9100/auth/oauth/authorize
              user-info-uri: http://localhost:9100/auth/userinfo
              user-name-attribute: username