#see: https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html

spring:
  profiles:
    active: @spring.profiles.active@

zk:
  homepage: /secure/main
  zul-view-resolver-prefix: /zul

server:
  error:
    whitelabel:
      enabled: false
  servlet:
    context-path: /kayros
    session:
      cookie:
        path: /kayros
  port: 8443
  ssl:
    key-store-password: zWx6bv-YTePQ%1qtGtnI
    key-store: classpath:kayrosWebappKeyStore.p12
    key-store-type: PKCS12
    key-alias: kayros-webapp

feign:
  hystrix:
    enabled: true
    
kairos-clock-service:
  ribbon:
    ReadTimeout: 1000
    ConnectTimeout: 1000   
    MaxAutoRetriesNextServer: 4
    MaxAutoRetries: 2
    
kairos-employee-service:
  ribbon:
    ReadTimeout: 1000
    ConnectTimeout: 1000   
    MaxAutoRetriesNextServer: 4
    MaxAutoRetries: 2

kayros-webapp:
  clockin:
    latency: 1

--- # Profile dev 

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:4001/eureka  
    
spring:
  profiles: dev
  application:
    name: kairos-webapp
  security: 
    oauth2:
      client:
        registration:
          kayrosclient:
            client-id: kayrosclientid
            client-secret: secret
            client-name: kayros
            scope: user_info,read,write
            redirect-uri: https://localhost:8443/kayros/login/oauth2/code/kayrosclient
            client-authentication-method: basic
            authorization-grant-type: authorization_code
            provider: kayros-authserver-provider
        provider:
            kayros-authserver-provider:
              token-uri: http://localhost:9100/auth/oauth/token
              authorization-uri: http://localhost:9100/auth/oauth/authorize
              user-info-uri: http://localhost:9100/auth/userinfo
              user-name-attribute: username

--- # Profile test
              
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-one:4001/eureka  
    
spring:
  profiles: test
  application:
    name: kairos-webapp
  security: 
    oauth2:
      client:
        registration:
          kayrosclient:
            client-id: kayrosclientid
            client-secret: secret
            client-name: kayros
            scope: user_info,read,write
            redirect-uri: https://192.168.0.22:8443/kayros/login/oauth2/code/kayrosclient
            client-authentication-method: basic
            authorization-grant-type: authorization_code
            provider: kayros-authserver-provider
        provider:
            kayros-authserver-provider:
              token-uri: http://192.168.0.22:9100/auth/oauth/token
              authorization-uri: http://192.168.0.22:9100/auth/oauth/authorize
              user-info-uri: http://192.168.0.22:9100/auth/userinfo
              user-name-attribute: username  
              
--- # Profile prod              
              
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-one:4001/eureka  
    
spring:
  profiles: prod
  application:
    name: kairos-webapp
  security: 
    oauth2:
      client:
        registration:
          kayrosclient:
            client-id: kayrosclientid
            client-secret: secret
            client-name: kayros
            scope: user_info,read,write
            redirect-uri: https://kayros-webapp:8443/kayros/login/oauth2/code/kayrosclient
            client-authentication-method: basic
            authorization-grant-type: authorization_code
            provider: kayros-authserver-provider
        provider:
            kayros-authserver-provider:
              token-uri: http://authorization-server:9100/auth/oauth/token
              authorization-uri: http://authorization-server:9100/auth/oauth/authorize
              user-info-uri: http://authorization-server:9100/auth/userinfo
              user-name-attribute: username  
